### ISSUE TITLE
Change the color of the label

### ISSUE THREAD

**Issue by rajavijayavendan** [JulioWar/jw-bootstrap-switch-ng2#9]
I have to change the background-colour of the empty label to green on ON State and to red colour on OFF State.How can I accomplish that?

**Comment by JulioWar** [comment]
Hi @rajavijayavendan you can use css.
When the switch change the state. I am putting a specific class for each state, by default are `.bootstrap-switch-off` and `.bootstrap-switch-on`.

So you can do something like this:
```css
.bootstrap-switch-off {
    background: red;
}
.bootstrap-switch-off .bootstrap-switch-label {
    background: red;
}
```
